### ISSUE TITLE
Configuration does not persist

### ISSUE THREAD

**Issue by javieryanez** [hleb-albau/kafka-manager-docker#1]
The configuration does not persist because the volume is incorrectly indicated in the Dockerfile file, where _/kafka-manager/configuration_ is indicated, but the correct path is _/kafka-manager/conf_ , see in [https://github.com/yahoo/kafka-manager/tree/master/conf](https://github.com/yahoo/kafka-manager/tree/master/conf)

**Comment by hleb-albau** [comment]
Hi @javieryanez, fixed for latest tag. See https://hub.docker.com/r/hlebalbau/kafka-manager/tags/.
Please, test and close issue if its okey.
Thanks for issue ;)

**Comment by javieryanez** [comment]
Well, the title of the problem isn't really correct. The correct title should be'the path of volume is wrong'. To persist, it is necessary to use named volumes. This does not detract from the fact that the correction is good, it avoids creating a useless volume.

Thanks for the quick fix!
