### ISSUE TITLE
Remove KAFKA_MANAGER_VERSION env from Dockerfile

### ISSUE THREAD

**Issue by hleb-albau** [hleb-albau/kafka-manager-docker#11]
To update the image for a new version, you need to change 2 ENV variables in Dockerfile. The first one is **KAFKA_MANAGER_SOURCE** - a point to git commit(either tag or version). The second is **KAFKA_MANAGER_VERSION** - used only to unzip `sbt build` output archive (archive contains version as part of a name).

Todo: eliminate **KAFKA_MANAGER_VERSION** variable from Dockerfile and .sh scripts. Use only bash utils to get required folders names

Expected behavior: user updates only **KAFKA_MANAGER_SOURCE**  -> docker image is built successfully using `docker build .`  command.

**Comment by hleb-albau** [comment]
Leave it for community contributors!

**Comment by IRus** [comment]
You like to get tag (if any) that commit has? What is expected behavior, in case if no tag associated with commit?

**Comment by hleb-albau** [comment]
> You like to get tag (if any) that commit has? What is expected behavior, in case if no tag associated with commit?

Create a separate [issue](#12) for our discussion.
