### ISSUE TITLE
Move `latest` tag

### ISSUE THREAD

**Issue by kiblik** [hleb-albau/kafka-manager-docker#13]
Hi,
Please, can you move docker tag `latest` to real latest commit? At this moment is `stable` newer than `latest`
Thanks

**Comment by hleb-albau** [comment]
Nice catch, will fix tomorrow.

**Comment by hleb-albau** [comment]
Updated **latest** by **stable** image(you can verify by checksum).
Updated auto build rules:
![image](https://user-images.githubusercontent.com/2991991/55969839-a8564d00-5ca8-11e9-977d-9c4c5c0d408b.png)

**Comment by hleb-albau** [comment]
@kiblik Please, close if I resolved you issue.

**Comment by kiblik** [comment]
It works.
Thanks
