### ISSUE TITLE
For version 2.0.0.2, the log grow very fast

### ISSUE THREAD

**Issue by chwong1** [hleb-albau/kafka-manager-docker#15]
As title. Any method to make the log level to ERROR?

**Comment by hleb-albau** [comment]
Hi @chwong1,

**/kafka-manager/conf** folder contains various Kafka Manager configs. Log file config is amoung them. I suggest you to change log level to **ERROR** only for annoing packages.

Please, try to change log level on your own, and write about you progress here :)

**Comment by hleb-albau** [comment]
@chwong1 Any progress you can share with rest of us? :)

**Comment by hleb-albau** [comment]
Closing as inactive. Feel free to reopen, if you still need help :)
