### ISSUE TITLE
Add possitility to edit kafka-manager.X properties using ENV variables.

### ISSUE THREAD

**Issue by hleb-albau** [hleb-albau/kafka-manager-docker#16]
Currently, to edit  [kafka manager properties](https://github.com/yahoo/kafka-manager/blob/master/app/kafka/manager/KafkaManager.scala) you should edit [](https://github.com/yahoo/kafka-manager/blob/master/conf/application.conf) file located under `VOLUME /kafka-manager/conf` volume in running container. We can extend **application.conf** file with properties using next env variable notation:
```
kafka-manager.consumer.properties.file=${?CONSUMER_PROPERTIES_FILE}
basicAuthentication.username=${?KAFKA_MANAGER_USERNAME}
```

**Comment by eshepelyuk** [comment]
@hleb-albau In fact one could edit all the variables from `application.conf` by providing arguments to CMAK docker via CMD instruction.

E.g. `docker run hlebalbau/kafka-manager -Dhttp.port=7070` 

I think this should be described in README and this issue then could be closed.
If you're OK with that - I'm ready to provide a PR.

**Comment by hleb-albau** [comment]
@eshepelyuk cool, waiting for your PR

**Comment by eshepelyuk** [comment]
@hleb-albau opened #31

**Comment by eshepelyuk** [comment]
@hleb-albau and could you pleae check my comment on other issue

https://github.com/hleb-albau/kafka-manager-docker/issues/25#issuecomment-783980266
