### ISSUE TITLE
Container Died

### ISSUE THREAD

**Issue by mikeydiamonds** [hleb-albau/kafka-manager-docker#18]
I'm not sure what happened but the kafka manager container is no longer working. 
Docker logs state:
`No java installations was detected.
Please go to http://www.java.com/getjava/ and download`
Any idea what this could be? I tried to reinstall with the `stable` tag, same result.

**Comment by mikeydiamonds** [comment]
It works when pulling hlebalbau/kafka-manager:1.3.3.22

**Comment by hleb-albau** [comment]
Hi  @mikeydiamonds, i will recheck `stable` image today.

**Comment by hleb-albau** [comment]
Hm, last stable version seems work on my pc. Very strange behavior....
Also use `docker pull hlebalbau/kafka-manager:stable` to manually update tag version to latest version.
```
Digest: sha256:adb47955e2619d280caf30ac86279fe34a4cd118d341680b3351fec55f34261a
Status: Image is up to date for hlebalbau/kafka-manager:stable
```
