### ISSUE TITLE
Update build to reflect https://github.com/yahoo/CMAK repo renaming

### ISSUE THREAD

**Issue by hleb-albau** [hleb-albau/kafka-manager-docker#20]
Addition points:
- Consider to use actions instead of dockerhub build?

**Comment by franzmueller** [comment]
It looks like this fork already has the latest updates integrated (plus some additions for AWS CodeBuild): https://github.com/FairwayIQ/kafka-manager-docker

**Comment by hleb-albau** [comment]
@franzmueller if it's not complicated for you, please, provide PR(hint: for small changes, you can use github web editor)

**Comment by franzmueller** [comment]
Please have a look at #21

**Comment by hleb-albau** [comment]
Thanks for contributions, closed by #21
