### ISSUE TITLE
Build from master?

### ISSUE THREAD

**Issue by smlgbl** [hleb-albau/kafka-manager-docker#3]
Hi,

could you create a Docker image that gets built from latest master, instead of releases only?

Thank you!

**Comment by hleb-albau** [comment]
Updated scheme. Now there are **stable** and **latest** images. Currently struggling with building a master image. Each time it fails on downloading random dependency :(

**Comment by hleb-albau** [comment]
@smlgbl still struggling to build binaries. Seems there is a need to create a base image with dependencies.
See builds details here. https://cloud.docker.com/repository/registry-1.docker.io/hlebalbau/kafka-manager/hub-builddetail/bqeazmt48sxvylj6kvejag7

**Comment by hleb-albau** [comment]
@smlgbl Finaly checkout **master-48bb088** tag.

**Comment by smlgbl** [comment]
@hleb-albau Thank you very much for the quick resolution! Awesome work!
