### ISSUE TITLE
mention in documentation: host.docker.internal

### ISSUE THREAD

**Issue by Nicramus** [hleb-albau/kafka-manager-docker#30]
This is something for people who are not docker kaptains :D But i think it would be good to mention in documentation if you had running kafka/zookeper on docker host  you should use  **host.docker.internal**
Or maybe it's just some Windows problem because localhost just didn't work for me
`docker run -d -p 9000:9000 -e ZK_HOSTS="host.docker.internal:2181" hlebalbau/kafka-manager:stable`

**Comment by hleb-albau** [comment]
Yeah, networking staff a bit complicated for newcomers. Feel free to provide your PR :)

**Comment by eshepelyuk** [comment]
`host.docker.internal` is valid only for Windows and Mac, since there Docker doesn't run natively, but via some intermediate layers or in some setup - pure VMs.

It's only available on the latest Docker versions for Linux
https://github.com/docker/for-linux/issues/264

**Comment by eshepelyuk** [comment]
The README was rewritten some time recently to suggest running CMAK with own ZK instance only via docker-compose. Currently it is recommended way of using this docker image. Examples were provided as well.

Using provided docker-compose examples will eliminate the bug raised in a initial comment. 

So, I suggest to close this issue as no fixes needed.
@Nicramus wdyt ?

**Comment by eshepelyuk** [comment]
Well, I suppose this could be closed. @hleb-albau wdyt ?
