### ISSUE TITLE
transfer repo to @eshepelyuk

### ISSUE THREAD

**Issue by hleb-albau** [hleb-albau/kafka-manager-docker#41]
hey @eshepelyuk, do you ready to be repo owner? if so, you should delete fork, cuz it prevent me(github do not allow) to transfer repo. Also, dockerhub does not have option to transfer image ownership, so i can just make banner on the top with link to your image. Or maybe you know better options?

**Comment by eshepelyuk** [comment]
Hello

yes, let's transfer. I'll delete a fork.
About DockerHub - I planned to host images on GitHub Packages, so we may neglect it.

**Comment by hleb-albau** [comment]
next step is to add banner in docker hub for your docker image. When you will be ready, post image link here, i will change my repo description.

**Comment by eshepelyuk** [comment]
Hello @hleb-albau 

The location of new images will be 
https://github.com/eshepelyuk?tab=packages&repo_name=cmak-docker

**Comment by hleb-albau** [comment]
Hello, in process of family migration
A left link to this repo in original dockerhub image
Thanks and GL!
