### ISSUE TITLE
SASL/TLS

### ISSUE THREAD

**Issue by lconnell** [hleb-albau/kafka-manager-docker#42]
Are there any plans to support SASL/TLS?

**Comment by eshepelyuk** [comment]
I will be able to answer your question if you completely explain what do you mean ?
it is a docker of cmak, how it is related to sasl/tls ?

**Comment by lconnell** [comment]
The ability to connect to Zookeeper over TLS and authenticate via SASL.

**Comment by eshepelyuk** [comment]
sasl/tsl is not related to docker image. if cmak supports this - you can configure it, if not - you should create and issue in cmak repo.
