### ISSUE TITLE
cgroups v2 compatible java version

### ISSUE THREAD

**Issue by gnobironts** [hleb-albau/kafka-manager-docker#46]
The Java version currently shipped with the latest image of cmak-docker is openjdk 11.0.15 (by the tag jre-11)
This version is not compatible with cgroups v2, which can cause larger memory consumption (I am facing this problem on AKS clusters in version 1.25).

A solution could be to update the java version to 11.0.16 (and it's the version delivered with tag jre-11 since August 2022). Simply releasing a new version may be enough.

https://bugs.openjdk.org/browse/JDK-8230305

**Comment by eshepelyuk** [comment]
Hello @gnobironts 

PR is welcome, I d like to pin the version to 11.0.16.

you can fillow this guide

https://github.com/eshepelyuk/cmak-operator/blob/master/CONTRIBUTING.md
