### ISSUE TITLE
Update java base image

### ISSUE THREAD

**Issue by ST-DDT** [hleb-albau/kafka-manager-docker#8]
Currently the docker image uses Java8u131. But newer versions are available.
Would it be possible to update? IIRC the latest version is Java 8u201 / Java 11.

**Comment by hleb-albau** [comment]
Sure. Do you have the experience to run kafka-manager on java 11? Or we should stay on 8uXXX branch for now?

**Comment by ST-DDT** [comment]
In most cases you just have to add the modules that were removed from the jre 11. Aka fight the ClassNotFoundExceptions. But for now an uptodate java 8 is good enough.

**Comment by hleb-albau** [comment]
Updated to use always new java version.
Built new master release(latest, not stable) with updated java.
So, is it done?

**Comment by ST-DDT** [comment]
Yes. Thanks for your time.
